import api from './index'

export const getLists = (appId) => api.get(`/apps/${appId}/lists/`)
export const getList = (appId, id) => api.get(`/apps/${appId}/lists/${id}/`)
export const createList = (appId, data) => api.post(`/apps/${appId}/lists/`, data)
export const updateList = (appId, id, data) => api.put(`/apps/${appId}/lists/${id}/`, data)
export const deleteList = (appId, id) => api.delete(`/apps/${appId}/lists/${id}/`)
export const getListFields = (listId) => api.get(`/lists/${listId}/fields/`)
export const createListField = (listId, data) => api.post(`/lists/${listId}/fields/`, data)
export const updateListField = (listId, id, data) => api.put(`/lists/${listId}/fields/${id}/`, data)
export const deleteListField = (listId, id) => api.delete(`/lists/${listId}/fields/${id}/`)
export const getListViews = (listId) => api.get(`/lists/${listId}/views/`)
export const createListView = (listId, data) => api.post(`/lists/${listId}/views/`, data)
export const updateListView = (listId, id, data) => api.put(`/lists/${listId}/views/${id}/`, data)
export const deleteListView = (listId, id) => api.delete(`/lists/${listId}/views/${id}/`)
export const getFormSchema = (appId, listId) => api.get(`/apps/${appId}/lists/${listId}/form_schema/`)
