# Generated by Django 5.2.14 on 2026-05-13 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='metadata.contenttype')),
            ],
            options={
                'db_table': 'content_types',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='applications.application')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.contenttype')),
            ],
            options={
                'db_table': 'lists',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('search_type', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('validators', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='metadata.contenttype')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fieldtype')),
            ],
            options={
                'db_table': 'content_type_fields',
                'ordering': ['order', 'created_at'],
                'unique_together': {('content_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ListField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('search_type', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('validators', models.JSONField(blank=True, default=list)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fieldtype')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='metadata.list')),
            ],
            options={
                'db_table': 'list_fields',
                'ordering': ['order', 'created_at'],
                'unique_together': {('list', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ListView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url_key', models.CharField(default='default', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='metadata.list')),
            ],
            options={
                'db_table': 'list_views',
                'ordering': ['order', 'created_at'],
                'unique_together': {('list', 'url_key')},
            },
        ),
    ]
