# Generated by Django 5.2.14 on 2026-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_remove_list_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='listview',
            name='list',
        ),
        migrations.AddField(
            model_name='list',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ListField',
        ),
        migrations.DeleteModel(
            name='ListView',
        ),
    ]
