# Generated by Django 5.2.14 on 2026-05-13 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.list'),
        ),
    ]
