# Generated by Django 5.2.14 on 2026-05-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_navigation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='url_prefix',
        ),
    ]
